apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    team: plataform-engineering
    env: production
    severity: critical
    giropops: strigus
spec:
  ports:
  - port: 9113
    name: metrics
  selector:
    app: nginx
