global:
route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 15s
  group_interval:
  repeat_interval: 5m

  routes:
  - receiver: MongoDBAlert
    match:
      team: mongodb

  - receiver: AlertWebApi
    match:
      team: webapi

receivers:
- name: Default
  webhook_configs:
    - url: ''
- name: MongoDBAlert
  webhook_configs:
    - url: ''
- name: AlertWebApi
  webhook_configs:
    - url: ''



