global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
  external_labels:
    aula: kubedev-prometheus

rule_files:
  - alert-rules.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          grupo: "Prometheus"
  
  - job_name: Api
    scrape_interval: 5s
    scrape_timeout: 1s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["http://localhost:8080/metrics"]
        labels:
          grupo: "webapi"
  - job_name: MongoDBExporter
    static_configs:
      - targets: ["mongodbexporter:9216"]
        labels:
          grupo: "MongoDB"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - 'alertmanager:9093'