groups:
  - name: Meus primeiros alertas
    rules: 
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      annotations:
        title: 'a maquina {{ $labels.instance }} está fora!'
        description: 'retornar a maquina {{ $labels.instance }}'
      labels:
        severity: 'critical'
    - alert: LoadAVG
      expr: node_load1 < 1.0
      for: 1m
      annotations:
        description: '{{ $labels.instance }} está com o load_average alto'
        summary: '{{ $labels.instance }} esta com load alto'
        value: '{{ $value }}'
    - alert: DiskUsage
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 90
      labels:
        instance: '{{ $labels.instance }}:{{ $labels.mountpoint }}'
      annotations:
        value: '{{ humanize $value }}'
